version: '2'
services:
    matchingjob-app:
        image: matchingjob
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://matchingjob-mysql:3306/matchingjob?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    matchingjob-mysql:
        extends:
            file: mysql.yml
            service: matchingjob-mysql
